spring.application.name=warehouse-mcp

server.port=8087

spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true
    
otel.propagators=tracecontext,b3
otel.resource.attributes.deployment.environment=dev
otel.resource.attributes.service.name=warehouse
otel.resource.attributes.service.namespace=default

management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

# This is the base URL for Warehouse API (intended to be replaced with environment dependant value)
application.warehouse-base-url=http://localhost:8086