spring.application.name=store
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}

spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true
spring.ai.chat.observations.include-error-logging=true
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
spring.ai.tools.observations.include-content=true

otel.propagators=tracecontext,b3
otel.resource.attributes.deployment.environment=dev
otel.resource.attributes.service.name=store
otel.resource.attributes.service.namespace=default

management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

dapr.pubsub.name=pubsub
dapr.pubsub.topic=shipments

#shipping-mcp.baseUrl=http://localhost:7777
#shipping-mcp.endpoint=mcp/reshapr/springio.workshop.v1.ShippingService/v1

spring.ai.mcp.client.streamable-http.connections.shipping-mcp.url=http://localhost:7777
spring.ai.mcp.client.streamable-http.connections.shipping-mcp.endpoint=/mcp/reshapr/springio.workshop.v1.ShippingService/v1

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces