spring.application.name=store
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.chat.observations.log-prompt=true

management.tracing.sampling.probability=1
management.opentelemetry.resource-attributes."service.name"=${spring.application.name}
management.endpoints.web.exposure.include=*
management.endpoint.configprops.show-values=always