spring.application.name=store
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}

spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true
spring.ai.chat.observations.include-error-logging=true
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
spring.ai.tools.observations.include-content=true

otel.propagators=tracecontext,b3
otel.resource.attributes.deployment.environment=dev
otel.resource.attributes.service.name=store
otel.resource.attributes.service.namespace=default

management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

dapr.pubsub.name=pubsub
dapr.pubsub.topic=pubsubTopic

warehouse.url=http://warehouse:8080

shipping.url=localhost:9091

spring.ai.mcp.client.streamable-http.connections.warehouse-mcp.url=http://localhost:8087

logging.level.org.springframework.ai.mcp=DEBUG

